
CREATE TABLE ALANDA_OBJECT_TYPE(
    "GUID" NUMBER NOT NULL,
    "NAME" VARCHAR(255) NOT NULL UNIQUE,
    "ADDITIONAL_PROPERTY_CONFIG" CLOB,
    PRIMARY KEY(GUID)
);

CREATE TABLE ALANDA_OBJECT(
   "GUID" NUMBER NOT NULL,
   "OTID" NUMBER NOT NULL,
   "CREATED" DATE,
   "CREATEUSER" NUMBER(38,0),
   "LASTUPDATE" DATE,
   "UPDATEUSER" NUMBER(38,0),
   PRIMARY KEY(GUID),
   FOREIGN KEY(OTID)
        REFERENCES ALANDA_OBJECT_TYPE(GUID)
);

CREATE TABLE ALANDA_OBJECT_PROPERTIES(
     "GUID" NUMBER NOT NULL,
     "OID" NUMBER NOT NULL,
     "KEY" VARCHAR2(255),
     "VALUE" VARCHAR2(255),
     "TYPE" VARCHAR2(255),
     PRIMARY KEY(GUID),
     FOREIGN KEY(OID)
         REFERENCES ALANDA_OBJECT(GUID)
);
